### ISSUE TITLE
http://www.rand-img.com is broken

### ISSUE THREAD

**Issue by peter279k** [rand-img/RandImgProvider#2]
## Detailed description

As title.

## Context

It seems that the `http://www.rand-img.com` domain is broken.

## Possible implementation

Fix this link and make this domain and related API service available to be accessed.

## Your environment

N/A

**Comment by SiroDiaz** [comment]
Hi @peter279k, the project rand-img has been shut down. I'm going to archive this repository in the following days. Thanks for your support.

**Comment by peter279k** [comment]
Thanks for your reply and your explanation ☺️!
